In [2]:
import numpy as np

# ES1

In [3]:
Z = np.arange(1, 10)
Z

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
X = np.array([np.array(Z[-i]) for i in range(1, 10)])
X

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

# ES2

In [5]:
l = [[k*i for i in range(1, 10)] for k in range(1, 10)]
l

[[1, 2, 3, 4, 5, 6, 7, 8, 9],
 [2, 4, 6, 8, 10, 12, 14, 16, 18],
 [3, 6, 9, 12, 15, 18, 21, 24, 27],
 [4, 8, 12, 16, 20, 24, 28, 32, 36],
 [5, 10, 15, 20, 25, 30, 35, 40, 45],
 [6, 12, 18, 24, 30, 36, 42, 48, 54],
 [7, 14, 21, 28, 35, 42, 49, 56, 63],
 [8, 16, 24, 32, 40, 48, 56, 64, 72],
 [9, 18, 27, 36, 45, 54, 63, 72, 81]]

In [8]:
n = 1
l = [1]
while n < 100:
    i = 2
    p = False
    while i <= n:
        if n % i == 0 and p == False:
            l.append(n)
            p = True
        i += 1
    n += 1  


In [7]:
n=0
i=0
l = []
while n < 100:
    i += 1
    count = 1
    for j in range(2, i):
        if i % j == 0:
            count = 0
            break
    if count == 1:
        l.append(i)
        n += 1
np.array(l)

array([  1,   2,   3,   5,   7,  11,  13,  17,  19,  23,  29,  31,  37,
        41,  43,  47,  53,  59,  61,  67,  71,  73,  79,  83,  89,  97,
       101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163,
       167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233,
       239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311,
       313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389,
       397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463,
       467, 479, 487, 491, 499, 503, 509, 521, 523])

# ES4

In [9]:
Z = np.arange(2, 100)
X = np.array([Z[i - 1] + Z[i - 2] for i in range(1, 11)])
X

array([101,   5,   7,   9,  11,  13,  15,  17,  19,  21])

In [10]:
l = []
l.append(1)
l.append(1)
[l.append(l[k - 1] + l[k - 2]) for k in range(2,10)]
Z = np.array(l)
Z

array([ 1,  1,  2,  3,  5,  8, 13, 21, 34, 55])

In [11]:
dimB = 10
bersaglio = np.ones((dimB,dimB), dtype = np.int64)
bersaglio
for i in range(1,5):
    bersaglio[i:10-i, i:10-i] = i+1
bersaglio

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 2, 2, 2, 2, 2, 2, 2, 2, 1],
       [1, 2, 3, 3, 3, 3, 3, 3, 2, 1],
       [1, 2, 3, 4, 4, 4, 4, 3, 2, 1],
       [1, 2, 3, 4, 5, 5, 4, 3, 2, 1],
       [1, 2, 3, 4, 5, 5, 4, 3, 2, 1],
       [1, 2, 3, 4, 4, 4, 4, 3, 2, 1],
       [1, 2, 3, 3, 3, 3, 3, 3, 2, 1],
       [1, 2, 2, 2, 2, 2, 2, 2, 2, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int64)

# ES5

In [12]:
Z = np.arange(1, 15)
Z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
np.array([np.array(Z[i:i+4]) for i in range(0, 11)])

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

# ES10

In [14]:
misurazioni = np.random.normal(19, 5, 1000)
indici = np.random.randint(0, 1000, 20)
misurazioni[indici] = 9999.9
misurazioni

array([2.16301387e+01, 2.23898850e+01, 2.36447886e+01, 1.58199423e+01,
       2.05618327e+01, 2.15083311e+01, 1.40400863e+01, 2.19561206e+01,
       2.50044738e+01, 1.88201364e+01, 1.41789159e+01, 1.84342989e+01,
       1.47375828e+01, 2.06456700e+01, 2.55710289e+01, 2.31100454e+01,
       1.35115512e+01, 9.99990000e+03, 1.12846867e+01, 1.60912089e+01,
       2.10063053e+01, 2.68010122e+01, 1.88885375e+01, 2.52594994e+01,
       2.25289279e+01, 1.81069554e+01, 1.62986746e+01, 8.74724660e+00,
       9.34562393e+00, 2.03132463e+01, 9.99990000e+03, 2.18350465e+01,
       2.36641872e+01, 1.91170248e+01, 9.99990000e+03, 1.80513289e+01,
       2.61921582e+01, 2.09260156e+01, 2.01550389e+01, 2.24533122e+01,
       2.37709928e+01, 2.32380759e+01, 2.17568011e+01, 2.97136564e+01,
       1.94843892e+01, 2.74632888e+01, 1.96956333e+01, 1.48374744e+01,
       1.69270021e+01, 1.87857435e+01, 1.65977801e+01, 1.77625807e+01,
       1.70720569e+01, 2.30217484e+01, 2.01216599e+01, 2.29553624e+01,
      

In [15]:
indici

array([ 17, 129, 692, 963, 820, 476, 795,  30, 104, 528, 429,  30, 268,
       809,  34, 422, 503, 613, 364, 868])

In [16]:
indici = np.random.choice(np.arange(0, 1000), size = 20, replace = False)
indici

array([240, 686, 173, 782, 699, 931,  24, 399, 864, 181, 392,  44, 408,
       309, 271, 502, 603, 993, 847, 813])