In [17]:
import numpy as np

## Il Broadcast

In [18]:
array_1 = np.array([1, 2, 3, 4, 5])
array_1 * 2

array([ 2,  4,  6,  8, 10])

In [19]:
np.exp(array_1)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [20]:
np.sqrt(array_1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [21]:
array_1 + 10

array([11, 12, 13, 14, 15])

In [22]:
array_2 = np.array([-1, -2, -3, -4, -5])
array_2

array([-1, -2, -3, -4, -5])

In [23]:
array_1 * array_2 # dimensioni uguali

array([ -1,  -4,  -9, -16, -25])

In [37]:
matrice_1 = np.ones((5, 5))
matrice_2 = np.random.uniform(0, 1, (5, 1))
matrice_1 + matrice_2 # o 1 righa / colonna o tutta

array([[1.3150134 , 1.3150134 , 1.3150134 , 1.3150134 , 1.3150134 ],
       [1.07117156, 1.07117156, 1.07117156, 1.07117156, 1.07117156],
       [1.40273976, 1.40273976, 1.40273976, 1.40273976, 1.40273976],
       [1.05079617, 1.05079617, 1.05079617, 1.05079617, 1.05079617],
       [1.90500944, 1.90500944, 1.90500944, 1.90500944, 1.90500944]])

In [38]:
matrice_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
matrice_2

array([[0.3150134 ],
       [0.07117156],
       [0.40273976],
       [0.05079617],
       [0.90500944]])

In [42]:
matrice_5 = 5 * np.ones((5, 5))
matrice_5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [43]:
np.roll?