In [2]:
import numpy as np

In [4]:
altezze = np.random.normal(178, 10, (5, 7))
altezze

array([[188.3952198 , 195.07728097, 168.47496741, 192.28100085,
        183.62561204, 162.09360218, 163.85535591],
       [187.13185648, 191.60863497, 185.91071416, 187.07040877,
        182.21057865, 191.37113311, 185.17066562],
       [182.34021763, 167.91923564, 155.85145553, 182.35431685,
        146.08946115, 182.76812302, 161.51159377],
       [192.40700385, 188.71650043, 182.47833173, 177.71202887,
        174.36624167, 180.14553523, 168.19301545],
       [176.89744528, 166.73210237, 165.19328805, 170.50207557,
        172.6685132 , 194.00865648, 155.43480048]])

In [5]:
np.max(altezze)

195.07728096847646

In [6]:
np.min(altezze)

146.08946114534905

In [7]:
array_2d = np.array([[1., 2., 3.], [4., 5., 6.]])
array_2d

array([[1., 2., 3.],
       [4., 5., 6.]])

In [8]:
array_2d.shape # shape attributo

(2, 3)

In [9]:
array_2d_casuale = np.random.uniform(0., 1., (8, 2))
array_2d_casuale

array([[0.9309751 , 0.14569396],
       [0.43570585, 0.60394556],
       [0.14669076, 0.99378574],
       [0.75379797, 0.46080474],
       [0.17252965, 0.61904622],
       [0.92077836, 0.39992508],
       [0.29140216, 0.87262144],
       [0.76808935, 0.25168355]])

In [10]:
array_2d_casuale.shape

(8, 2)

### Elemento

In [11]:
array_2d_casuale[3, 1]

0.46080474031680685

### Colonna

In [12]:
array_2d_casuale[:, 0]

array([0.9309751 , 0.43570585, 0.14669076, 0.75379797, 0.17252965,
       0.92077836, 0.29140216, 0.76808935])

### Riga

In [13]:
array_2d_casuale[3, :]

array([0.75379797, 0.46080474])

### Blocco

In [ ]:
array_2d_casuale[2:5, :]

### Assegnazione

In [ ]:
array_2d_casuale[2:5, :] = 1.
array_2d_casuale

# Esercizio 
Creare un array 1d del tipo [0,1,0,1,0,1,0,1,0.........]

In [ ]:
n = 1000000

In [ ]:
%%timeit
# Soluzione numpy
array_1d = np.zeros(n, dtype = np.int8)
array_1d[::2] = 1

In [ ]:
%%timeit
# Soluzione Python
l = np.array([i%2 for i in range(0, n)])
l

Creare un arrey 2d 0,1

In [ ]:
array = np.zeros((11, 5), dtype = np.int8)
array[1::2, ::2] = 1
array[::2, 1::2] = 1
array

In [ ]:
array_1d =np.arange(1, 20)
array_1d

In [ ]:
array_1d[:5] = -1
array_1d

In [ ]:
array_1d[::5] = -1
array_1d

In [15]:
array_1d = np.arange(0, 5)
array_1d

array([0, 1, 2, 3, 4])

In [16]:
resto_fa_zero = array_1d % 2 == 0
resto_fa_zero

array([ True, False,  True, False,  True])

In [17]:
array_1d[resto_fa_zero] # solo elementi pari, indicizzazone booleana, pag 91

array([0, 2, 4])

In [18]:
array_1d[resto_fa_zero] = 999
array_1d

array([999,   1, 999,   3, 999])

In [ ]:
array_1d = np.random.uniform(0., 1., 10) 
array_1d

In [ ]:
array_1d[np.array([1, 2, 3])] # indicizzazione con array di indici o fancy-index

In [ ]:
array_1d[np.array([1, 2, 3])] = 999
array_1d