In [1]:
import numpy as np

In [2]:
lista = [1, 2, 3, 4]

In [3]:
type(lista)

list

In [4]:
array = np.array(lista)

In [5]:
array

array([1, 2, 3, 4])

In [6]:
type(array)

numpy.ndarray

In [7]:
3*array

array([ 3,  6,  9, 12])

In [8]:
3*lista

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [9]:
10 + array

array([11, 12, 13, 14])

In [10]:
array

array([1, 2, 3, 4])

In [11]:
a = array.copy()

In [12]:
a

array([1, 2, 3, 4])

In [13]:
b = np.array(lista[::-1])
b

array([4, 3, 2, 1])

In [14]:
a+b

array([5, 5, 5, 5])

In [15]:
zeri = np.zeros(10, dtype = np.int8)
zeri

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [16]:
uni = np.ones(10)
uni

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.random.uniform(size=10)

array([0.07163847, 0.49619894, 0.81434635, 0.30827558, 0.9136189 ,
       0.15898564, 0.3509203 , 0.96128211, 0.27878405, 0.1406625 ])

In [21]:
alice = np.random.randint(1, 7, 10)

In [22]:
bob = np.random.randint(1, 7, 10)

In [23]:
print(f"Lanci di Alice: {alice}")
print(f"Lanci di Bob: {bob}")

Lanci di Alice: [3 5 4 1 1 4 2 4 3 6]
Lanci di Bob: [3 4 4 3 1 5 2 2 1 1]


In [25]:
alice.dtype

dtype('int32')

In [27]:
alice_vince = alice > bob

In [28]:
alice_vince

array([False,  True, False, False, False, False, False,  True,  True,
        True])

In [29]:
type(alice_vince)

numpy.ndarray

In [30]:
alice_vince.dtype

dtype('bool')

In [31]:
alice[alice_vince] # indicizzazione booleana

array([5, 4, 3, 6])

In [32]:
bob[alice_vince]

array([4, 2, 1, 1])

In [34]:
np.arange(3, 20, 3)

array([ 3,  6,  9, 12, 15, 18])

In [35]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
np.linspace(0.0, 5.0, 11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [43]:
np.random.uniform(0., 10., 5) # reale

array([0.80974479, 5.2176617 , 6.87449485, 1.21102889, 8.44922127])

In [44]:
np.random.randint(1, 7, 5)

array([3, 6, 2, 5, 4])

In [47]:
np.random.choice(["Testa", "Croce"], 20)

array(['Croce', 'Croce', 'Testa', 'Testa', 'Croce', 'Testa', 'Croce',
       'Croce', 'Croce', 'Testa', 'Testa', 'Testa', 'Croce', 'Testa',
       'Testa', 'Croce', 'Testa', 'Croce', 'Testa', 'Croce'], dtype='<U5')

In [48]:
np.random.choice(["2", "Croce"], 10, p = [0.7, 0.3])

array(['Testa', 'Testa', 'Testa', 'Testa', 'Croce', 'Testa', 'Croce',
       'Testa', 'Testa', 'Croce'], dtype='<U5')

In [49]:
np.random.normal(1., 1., 10)

array([2.31925354, 0.74105422, 1.38690355, 0.71008991, 1.08372122,
       2.60680683, 2.10567858, 2.00480251, 0.71654503, 2.43585891])