In [1]:
import numpy as np

# PRIME OPERAZIONI DEGLI ARRAY

In [3]:
a1 = np.array((1,2,3))                 #array ad tupla

a2 = np.array([1.6,-1,3], np.uint8)    #array da lista con specifica di tipo

a3 = np.arange(10, dtype = float)      #array da range[0..stop) con passo 1 e specifica di tipo

a4 = np.arange(4,10,2)                 #array da range [start..stop) on passo 2

a5 = np.linspace(0,10,5)               #array di 5 numeri equamente distibuiti in [start..stop], si può usare dtype

print("a1: ", a1); print("a2: ",a2); print("a3: ", a3); print("a4: ", a4); print("a5: ",a5)

a1:  [1 2 3]
a2:  [  1 255   3]
a3:  [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
a4:  [4 6 8]
a5:  [ 0.   2.5  5.   7.5 10. ]


In [5]:
a6 = np.zeros(5, dtype = np.uint)     #array di 0 con specifica di tipo (per default float64)

a7 = np.zeros(5)                      #array di 1 (per default float64)

a8 = np.zeros((2,3))                  #array di 0 con dimensioni specificate

print("a6: ",a6); print("a7: ", a7); print("a8: \n", a8)

a6:  [0 0 0 0 0]
a7:  [0. 0. 0. 0. 0.]
a8: 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
a8.fill(3)
print(a8)

[[3. 3. 3.]
 [3. 3. 3.]]


In [12]:
mat1 = np.random.rand(2,3)                    #matrice 2X3 di valori casuali reali in [0..1)

mat2 = np.random.randint(1,7, size =(2,3))    #matrice 2X3 di valori casuali in teri in [1..7)

mat3 = np.random.randn(2,3)                   #matrice 2X3 di valori casuali reali campionati da una distizbuizione 
                                              #normale con m = 0 e dev = 1ùù

print("rand(2,3):\n", mat1); print("\n"); 
print("randint(1,7, size=(2,3)):\n", mat2); print("\n"); 
print("randn(2,3):\n", mat3)

rand(2,3):
 [[0.6892064  0.82834143 0.92166929]
 [0.90859213 0.45105212 0.59421959]]


randint(1,7, size=(2,3)):
 [[6 3 1]
 [4 4 3]]


randn(2,3):
 [[ 0.70409033 -2.80424676  0.00624093]
 [ 0.24991161 -0.60655495  0.28843299]]


In [16]:
dado = np.random.choice(['testa', 'croce'], size = 8, p=[0.8, 0.2])
dado

array(['croce', 'testa', 'testa', 'testa', 'testa', 'testa', 'testa',
       'croce'], dtype='<U5')

In [20]:
print(np.random.choice(['Qui', 'Quo', 'Qua'], size = 3, replace = False))

['Quo' 'Qua' 'Qui']


# LA FORMA DEGLI ARRAY

In [22]:
ndarray = np.array([[[1,2], [10,20], [100,100]]])
print(ndarray)
print("numero di dimensioni:", np.ndim(ndarray))             #anche ndarry.ndim
print("elementi per ogni dimensione:", np.shape(ndarray))    #anche ndarray.shape
print("elementi totali:", np.size(ndarray))                  #anche ndarray.size
print("tipo elementi:", ndarray.dtype)

[[[  1   2]
  [ 10  20]
  [100 100]]]
numero di dimensioni: 3
elementi per ogni dimensione: (1, 3, 2)
elementi totali: 6
tipo elementi: int32


In [23]:
array1 = ndarray.flatten()     #crea una copia a 1 dimensione dell'array
array2 = ndarray.ravel()       #mantiene un riferimento con l'array originale
array1[0] = 0
array2[1] = 0
print("array1: \n", array1); print("array2: \n", array2);
print("origine: \n", ndarray)    #modificato solo attraverso ravel

array1: 
 [  0   2  10  20 100 100]
array2: 
 [  1   0  10  20 100 100]
origine: 
 [[[  1   0]
  [ 10  20]
  [100 100]]]


In [27]:
array1.shape = (2,3)           #modifica la struttura
print(array1)
mat = ndarray.reshape(2,-1)    #restituisce un ndarray con struttura modificata
print(mat)

[[  0   2  10]
 [ 20 100 100]]
[[  1   0  10]
 [ 20 100 100]]


In [30]:
m = np.arange(24)                                 #vettore con elememti da 0  a 23
m = m.reshape(4,6)
print("m.shape", m.shape, "\n", m)
print("transpose.shape", np.transpose(m).shape)   #inverte lo shape; per le matrice fa la trasposta
print(m.T)

m.shape (4, 6) 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
transpose.shape (6, 4)
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [31]:
print("axis = None \n", np.roll(m,2))            #viene prima fatto il flatten e poi lo shift
print("axis = 0 \n", np.roll(m,1, axis = 0))     #shift delle interre righe
print("axis = 1 \n", np.roll(m, -1, axis = 1))   #shift a sinistra in ciascuna riga 

axis = None 
 [[22 23  0  1  2  3]
 [ 4  5  6  7  8  9]
 [10 11 12 13 14 15]
 [16 17 18 19 20 21]]
axis = 0 
 [[18 19 20 21 22 23]
 [ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
axis = 1 
 [[ 1  2  3  4  5  0]
 [ 7  8  9 10 11  6]
 [13 14 15 16 17 12]
 [19 20 21 22 23 18]]


# INDICIZZAZIONE

In [34]:
a = np.arange(12)          #vettore con elementi da 0 a 11
a = a.reshape(4,-1)        #lo strasforma in una matrice 4X3
print("a:\n", a)    
ls = a.tolist()            #restituisce la lista python corrispondente all'array
print("a.tolist():", ls)
a[1,2] = -1 
ls[1][2] = -2              #anche in Numpy si può usare questa notazione, ma è meno efficente
print("a[1]:", a[1])       #selezione l'elemento di indice 1, ovvero l'intera riga
print("ls[1]", ls[1])      #seleziona l'elemento di indice 1, ovvero l'intera riga

a:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
a.tolist(): [[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]]
a[1]: [ 3  4 -1]
ls[1] [3, 4, -2]


In [35]:
print(a[:-2])     #da 0 al penultimo elemento escluso
print(a[2:4])     #dall'elemento di indice 2 al 4 escluso
print(a[1:4:2])   #dall'emento di indice 1 al 4 escluso, passo2 
print(a[:,1:2])   #tutte le righe, dalla colona 1 alla 2 eclusa
print(a[:,1])     #tutti gli elementi della colonna di indice 1

[[ 0  1  2]
 [ 3  4 -1]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 3  4 -1]
 [ 9 10 11]]
[[ 1]
 [ 4]
 [ 7]
 [10]]
[ 1  4  7 10]
