# Verifica su Python e introduzione a Numpy
### COGNOME NOME

## ESERCIZIO 1
Il file *robots.txt* contiene un frammento del vero file *robots.txt* di un importante quotidiano online. Tutte le righe che iniziano con la parola chiave `Disallow:` contengono le URL di pagine del quotidiano alle quali i software automatici di web crawling o di indicizzazione non dovrebbero mai accedere. La prima directory della URL indica la tipologia di notizia a cui punta l'URL. Per esempio la riga `Disallow: /economia/finanza-personale/2010/Prova-Metadati_a1b5a008-f178-11df-8c4b-00144f02aabc.shtml`fa riferimento a una notizia di **economia**.

Crea un programma in Python 3 che legga il file e generi un dizionario in cui:
* la chiave è la tipologia di notizia,
* il valore è il numero di notizie di quella tipologia.

In [61]:
f = open("robots.txt","r") 
print(f.read())

# item
Disallow: /politica/10_febbraio_05/sabrina_ferilli_non_sono_la_sora_palin_5d9b4bb8-1224-11df-b50d-00144f02aabe.shtml
Disallow: /esteri/07_novembre_24/allam_8b31e72c-9a84-11dc-a3e4-0003ba99c53b.shtml
Disallow: /cronache/09_ottobre_31/marrazzo_quinto_indagato_ceb2b5c2-c5f1-11de-a5d7-00144f02aabc.shtml
Disallow: /cronache/10_settembre_20/napoli-donna-uccisa-in-auto_d6588bc2-c48c-11df-be0b-00144f02aabe.shtml
Disallow: /politica/11_gennaio_10/prova_dbfc1a72-1ce7-11e0-a4b5-00144f02aabc.shtml
Disallow: /cronache/10_ottobre_19/Prova_NONToccare_1137fc74-db6b-11df-a6e9-00144f02aabc.shtml
Disallow: /sport/10_ottobre_05/prova_articoloNOTOUCH_4957ef9a-d05a-11df-9b01-00144f02aabc.shtml
Disallow: /economia/finanza-personale/2010/Prova-Metadati_a1b5a008-f178-11df-8c4b-00144f02aabc.shtml
Disallow: /scienze_e_tecnologie/speciali/2010/corriere-mobile/notizie/test_6eec41ea-3364-11df-82b0-00144f02aabe.shtml
Disallow: /economia/speciali/2010/la-crisi-greca/notizie/test1_db95ec2e-520e-11df-9da0-00144f

## ESERCIZIO 2
Crea un array di numpy che contenga tutti i numeri interi tra 2 e 1000 (estremi inclusi), ma nel quale tutti i numeri divisibili per 7 sono sostituiti da uno 0. Infine crea un array contenente tutti i numeri interi tra 2 e 1000 (estremi inclusi) ma privo di tutti i numeri divisibili per 7.

In [95]:
import numpy as np
array = np.arange(2,10001)
array

array([    2,     3,     4, ...,  9998,  9999, 10000])

In [46]:
array2 = np.arange(5,997,7)
print(array2)

[  5  12  19  26  33  40  47  54  61  68  75  82  89  96 103 110 117 124
 131 138 145 152 159 166 173 180 187 194 201 208 215 222 229 236 243 250
 257 264 271 278 285 292 299 306 313 320 327 334 341 348 355 362 369 376
 383 390 397 404 411 418 425 432 439 446 453 460 467 474 481 488 495 502
 509 516 523 530 537 544 551 558 565 572 579 586 593 600 607 614 621 628
 635 642 649 656 663 670 677 684 691 698 705 712 719 726 733 740 747 754
 761 768 775 782 789 796 803 810 817 824 831 838 845 852 859 866 873 880
 887 894 901 908 915 922 929 936 943 950 957 964 971 978 985 992]


In [100]:
array=np.clip(array, 0, 7)
array

array([2, 3, 4, ..., 5, 5, 5])

## ESERCIZIO 3
Dato `n`numero intero dispari maggiore o uguale a 5 crea una matrice di numpy che abbia la struttura seguente esemplificata, per il caso `n=7`. 

`[[0.35012821 0.13462121 0.38492916 0.51293425 0.25255366 0.85166111 0.59550361]
 [0.47468085 0.         0.         1.         0.         0.         0.18300893]
 [0.23703845 0.         0.         1.         0.         0.         0.89905447]
 [0.52372585 1.         1.         1.         1.         1.         0.95780342]
 [0.51881137 0.         0.         1.         0.         0.         0.03430885]
 [0.09985312 0.         0.         1.         0.         0.         0.78938087]
 [0.37453082 0.21909742 0.6154127  0.89541758 0.79158936 0.68202705 0.82876577]`
 
La cornice della matrice deve essere composta di numeri pseudocasuali compresi tra 0 e 1, mentre l'interno deve essere riempito di 0 tranne nella riga e nella colonna mediane, le quali conterrano degli 1.
 

In [88]:
matrice= np.random.uniform(0.,7.,(7,7))
matrice

array([[4.06699688, 0.60605929, 4.55446302, 2.23283418, 0.96672336,
        3.00513199, 6.82819737],
       [5.04003347, 2.70764373, 6.75801141, 5.46892086, 0.87057371,
        4.82808536, 2.7063135 ],
       [2.41064703, 4.28197088, 6.96794893, 1.82761028, 6.38439412,
        0.12561834, 4.00155225],
       [0.63460948, 0.93499775, 3.56094198, 0.69772427, 0.42782484,
        2.64186528, 4.11035452],
       [5.70604523, 2.27165011, 5.20910747, 6.53397601, 6.9822119 ,
        0.16886393, 5.334528  ],
       [1.6191444 , 5.0182199 , 1.88676254, 5.84175804, 1.59948482,
        3.45696412, 2.49316464],
       [4.70512133, 2.26118766, 1.05168576, 3.78871073, 1.66830716,
        1.7837807 , 5.30146364]])

In [93]:
matrice[1:6,1:6]=1 
matrice

array([[4.06699688, 0.60605929, 4.55446302, 2.23283418, 0.96672336,
        3.00513199, 6.82819737],
       [5.04003347, 1.        , 1.        , 1.        , 1.        ,
        1.        , 2.7063135 ],
       [2.41064703, 1.        , 1.        , 1.        , 1.        ,
        1.        , 4.00155225],
       [0.63460948, 1.        , 1.        , 1.        , 1.        ,
        1.        , 4.11035452],
       [5.70604523, 1.        , 1.        , 1.        , 1.        ,
        1.        , 5.334528  ],
       [1.6191444 , 1.        , 1.        , 1.        , 1.        ,
        1.        , 2.49316464],
       [4.70512133, 2.26118766, 1.05168576, 3.78871073, 1.66830716,
        1.7837807 , 5.30146364]])